spring.application.name=demo-for-spring-AI

spring.ai.google.genai.api-key=${PRIMARY_GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

app.gemini.secondary.api-key=${SECONDARY_GEMINI_API_KEY}
app.gemini.secondary.model=gemini-2.5-flash

